# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x02pb\"\x07\n\x05\x45mpty\"W\n\nGenericRes\x12\x1a\n\x06status\x18\x01 \x01(\x0e\x32\n.pb.Status\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\x05value\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_value\"\x18\n\nGenericReq\x12\n\n\x02id\x18\x01 \x01(\t*\x1b\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x42%Z#github.com/carlosCACB333/cb-grpc/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z#github.com/carlosCACB333/cb-grpc/pb'
  _globals['_STATUS']._serialized_start=144
  _globals['_STATUS']._serialized_end=171
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_GENERICRES']._serialized_start=29
  _globals['_GENERICRES']._serialized_end=116
  _globals['_GENERICREQ']._serialized_start=118
  _globals['_GENERICREQ']._serialized_end=142
# @@protoc_insertion_point(module_scope)
