# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: directory.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64irectory.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0c\x63ommon.proto\"\xc6\x01\n\x06\x44irRes\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x07\x63ontent\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08parentId\x18\x04 \x01(\tH\x01\x88\x01\x01\x12-\n\tcreatedAt\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\tupdatedAt\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\n\n\x08_contentB\x0b\n\t_parentId\"b\n\x0c\x43reateDirReq\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x07\x63ontent\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08parentId\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\n\n\x08_contentB\x0b\n\t_parentId2~\n\nDirService\x12&\n\x06\x43reate\x12\x10.pb.CreateDirReq\x1a\n.pb.DirRes\x12!\n\x06GetAll\x12\t.pb.Empty\x1a\n.pb.DirRes0\x01\x12%\n\x07GetById\x12\x0e.pb.GenericReq\x1a\n.pb.DirResb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'directory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DIRRES']._serialized_start=71
  _globals['_DIRRES']._serialized_end=269
  _globals['_CREATEDIRREQ']._serialized_start=271
  _globals['_CREATEDIRREQ']._serialized_end=369
  _globals['_DIRSERVICE']._serialized_start=371
  _globals['_DIRSERVICE']._serialized_end=497
# @@protoc_insertion_point(module_scope)
