# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import docker_pb2 as docker__pb2


class DockerSvcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteCode = channel.unary_stream(
                '/pb.DockerSvc/ExecuteCode',
                request_serializer=docker__pb2.ExecuteCodeReq.SerializeToString,
                response_deserializer=docker__pb2.ExecuteCodeResp.FromString,
                )


class DockerSvcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DockerSvcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteCode': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteCode,
                    request_deserializer=docker__pb2.ExecuteCodeReq.FromString,
                    response_serializer=docker__pb2.ExecuteCodeResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.DockerSvc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DockerSvc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/pb.DockerSvc/ExecuteCode',
            docker__pb2.ExecuteCodeReq.SerializeToString,
            docker__pb2.ExecuteCodeResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
