# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: docker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64ocker.proto\x12\x02pb\x1a\x0c\x63ommon.proto\",\n\x0e\x45xecuteCodeReq\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04lang\x18\x02 \x01(\t\"=\n\x0f\x45xecuteCodeResp\x12\x1a\n\x06status\x18\x01 \x01(\x0e\x32\n.pb.STATUS\x12\x0e\n\x06output\x18\x02 \x01(\t2G\n\tDockerSvc\x12:\n\x0b\x45xecuteCode\x12\x12.pb.ExecuteCodeReq\x1a\x13.pb.ExecuteCodeResp\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'docker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXECUTECODEREQ']._serialized_start=34
  _globals['_EXECUTECODEREQ']._serialized_end=78
  _globals['_EXECUTECODERESP']._serialized_start=80
  _globals['_EXECUTECODERESP']._serialized_end=141
  _globals['_DOCKERSVC']._serialized_start=143
  _globals['_DOCKERSVC']._serialized_end=214
# @@protoc_insertion_point(module_scope)
