# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb8\x02\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x11\n\tfirstName\x18\x03 \x01(\t\x12\x10\n\x08lastName\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\x13\n\x06gender\x18\x06 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x08password\x18\x07 \x01(\t\x12\x14\n\x07picture\x18\x08 \x01(\tH\x01\x88\x01\x01\x12\x12\n\x05phone\x18\t \x01(\tH\x02\x88\x01\x01\x12\x0e\n\x06status\x18\n \x01(\t\x12-\n\tcreatedAt\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\tupdatedAt\x18\x0c \x01(\x0b\x32\x1a.google.protobuf.TimestampB\t\n\x07_genderB\n\n\x08_pictureB\x08\n\x06_phoneb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=52
  _globals['_USER']._serialized_end=364
# @@protoc_insertion_point(module_scope)
